### ISSUE TITLE
Recreate releases/tags

### ISSUE THREAD

**Issue by MikeMcQuaid** [Long-live-shadowsocks/ShadowVPN#2]
Would be good to recreate these:
http://webcache.googleusercontent.com/search?q=cache:rhtxTpStLTQJ:https://github.com/clowwindy/ShadowVPN/releases+&cd=2&hl=en&ct=clnk&gl=us

**Comment by MikeMcQuaid** [comment]
e.g. https://github.com/mikemcquaid/ShadowVPN/releases

**Comment by MikeMcQuaid** [comment]
@Xuchenhao @DIYgod @aofall Any thoughts? If you give me access I don't mind doing so. Thanks!

**Comment by DIYgod** [comment]
Thank you for your attention.

Hope this can help you: https://github.com/Long-live-shadowsocks/ShadowVPN/releases

In addition, I have invited you to this organization.

**Comment by wangqiliang** [comment]
Recreating releases of this project is against the Criminal law of the people's Republic of China.
Thank you.

**Comment by cuteSakuraHime** [comment]
@wangqiliang
Where? I don't find that in the Criminal law and anything about GFW.

**Comment by cuteSakuraHime** [comment]
一盏一盏的灯在熄灭，四面八方的光源在消失，有的光线被强制阻断，而有人不愿成为一盏显眼的灯，自己变得黯淡。

我们生活的五光十色的世界，变成了一片黑色。

天黑了，那么睡觉吧，但愿长醉不复醒。

最后，我们变成了一群做梦的人，这个梦的名字叫，信息主权和网络安全的中国梦。

也许终有一天，一盏一盏的灯渐渐亮起，这些灯足够亮，以至于墙内人终于看到了，曾经一度被他们所支配的恐怖，还有被囚禁于长城中的那份屈辱。

那时，我们中的一人，将会抽掉承重的最后一块砖。

**Comment by ghost** [comment]
怎么点赞
